name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean package
      working-directory: my-java-api

    - name: Run Unit Tests
      run: mvn test
      working-directory: my-java-api

    - name: Run Functional Tests
      run: mvn verify
      working-directory: my-java-api

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-java-api:latest .
      working-directory: my-java-api

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-java-api:latest

    - name: Create Git Tag
      id: tag
      run: echo "tag=$(echo main-$(date +%Y%m%d%H%M%S))" >> $GITHUB_ENV

    - name: Set up Git Authentication
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}

    - name: Push Git Tag
      run: |
        git tag ${{ env.tag }}
        git push origin ${{ env.tag }}
